/*
 * Name: accel.c
 * Contributor(s):
 *    - Group5 (TUM systolic-array AI accelerator)
 * Description:
 *    - Baremetal self-checking functional test for the systolic-array
 *      accelerator integrated in the TUM student subsystem (SS1).
 *    - Runs a tiled GEMM driver over random signed 8-bit (INT8 baseline)
 *      matrices A and B (from accel_gemm_data.h). Each hardware launch uses
 *      runtime M/N/K dimensions and compact A/B/C tile layouts, then software
 *      accumulates partial C tiles and compares against a golden reference.
 *    - The test vectors and golden matrix are generated by
 *      sim/common/c_code/gen_accel_data.py and reproduce the RTL's signed,
 *      32-bit-wrapping accumulation bit-for-bit.
 * Notes:
 *    - Accelerator APB window base = 0x0151_0000 (new SoC: slot 1 = tum_ss).
 *    - Internal address decode uses PADDR[9:8]:
 *        00 -> matrix_buffer_ab  (A @ 0x00, B @ 0x40, CTRL @ 0x80)
 *        01 -> control_unit      (regmap @ 0x100)
 *        10 -> matrix_buffer_c   (DATA @ 0x200, CTRL @ 0x280)
 *    - Hardware array physical size is fixed by the build variant. Runtime
 *      M/N/K dimensions select compact tiles up to that physical size.
 *      Each 32-bit APB write packs 32/DATA_W elements (DATA_W = 8 -> four),
 *      least-significant lane first.
 */

#include <stdint.h>
#include "soc_ctrl.h"
#include "uart.h"
#include "accel_driver.h"
#include "accel_regs.h"
#include "accel_tiled_gemm.h"

// Result sink that the testbench / debugger can observe:
//   0xACCE5500 -> PASS, 0xBADD0000 | mismatch_count -> FAIL.
// main() additionally returns its status (0 = pass): crt0's postMain ORs in
// the done bit and writes it to the 0x01020380 status register, which the
// JTAG-driven tb_didactic polls to detect end-of-computation.
volatile uint32_t accel_result = 0u;

#ifdef FPGA
static void uart_print_hex32(uint32_t value) {
  uart_print("0x");
  for (int shift = 28; shift >= 0; shift -= 4) {
    write_serial("0123456789ABCDEF"[(value >> shift) & 0xFu]);
  }
}

static void uart_print_hex8(uint32_t value) {
  uart_print("0x");
  write_serial("0123456789ABCDEF"[(value >> 4) & 0xFu]);
  write_serial("0123456789ABCDEF"[value & 0xFu]);
}

static void accel_print_build_info(const char *label, uint32_t value) {
  uart_print(label);
  uart_print(" build=");
  uart_print_hex32(value);
  uart_print(" M=");
  uart_print_hex8(value & 0xFFu);
  uart_print(" N=");
  uart_print_hex8((value >> 8) & 0xFFu);
  uart_print(" K=");
  uart_print_hex8((value >> 16) & 0xFFu);
  uart_print(" DATA_W=");
  uart_print_hex8((value >> 24) & 0xFFu);
  uart_print("\n");
}
#endif

int main(void) {
#ifdef FPGA
  uart_init(25000000, 9600);
#else
  uart_init();
#endif
  uart_print("accel: start\n");

  // Bring the TUM subsystem out of reset and enable its clock.
  ss_init(ACCEL_SS);

#ifdef FPGA
  uint32_t hw_build_info = REG_BUILD_INFO;
  uint32_t sw_build_info = accel_expected_build_info();
  if (hw_build_info != sw_build_info) {
    uart_print("accel: BUILD INFO MISMATCH\n");
    uart_print("accel: sw variant ");
    uart_print(ACC_VARIANT);
    uart_print("\n");
    accel_print_build_info("accel: hw", hw_build_info);
    accel_print_build_info("accel: sw", sw_build_info);
    accel_result = 0xBADD0002u;
    return 2;
  }
#else
  if (!accel_build_info_matches()) {
    uart_print("accel: BUILD INFO MISMATCH\n");
    accel_result = 0xBADD0002u;
    return 2;
  }
#endif

  volatile uint32_t accum[ACC_M * ACC_N];

#ifndef ACCEL_USE_DOUBLE_BUFFER
#define ACCEL_USE_DOUBLE_BUFFER 0
#endif
  accel_tile_status_t status =
      accel_run_tiled_gemm(accum, (void *)0, ACCEL_USE_DOUBLE_BUFFER);
  if (status == ACCEL_TILE_TIMEOUT) {
    uart_print("accel: TIMEOUT waiting for tile\n");
    accel_result = 0xBADD0001u;
    return 1;
  }
  if (status != ACCEL_TILE_OK) {
    uart_print("accel: PERF FAIL\n");
    accel_result = 0xBADD0003u;
    return 3;
  }

  uint32_t mismatches = accel_count_mismatches(accum);

  if (mismatches == 0u) {
    uart_print("accel: PASS\n");
    accel_result = 0xACCE5500u;
    return 0; // exit status 0 -> tb_didactic reports JTAG RETURN OK
  }

  uart_print("accel: FAIL\n");
  accel_result = 0xBADD0000u | (mismatches & 0xFFFFu);
  return (int)(mismatches & 0x7FFFFFFFu); // nonzero -> tb_didactic FAILURE
}
