/*
 * Name: accel.c
 * Contributor(s):
 *    - Group5 (TUM systolic-array AI accelerator)
 * Description:
 *    - Baremetal self-checking functional test for the systolic-array
 *      accelerator integrated in the TUM student subsystem (SS1).
 *    - Streams random signed 8-bit (INT8 baseline) matrices A and B (from
 *      accel_gemm_data.h) through the accelerator, then reads back C = A * B and
 *      compares every element against a precomputed golden reference.
 *    - The test vectors and golden matrix are generated by
 *      sim/common/c_code/gen_accel_data.py and reproduce the RTL's signed,
 *      32-bit-wrapping accumulation bit-for-bit.
 * Notes:
 *    - Accelerator APB window base = 0x0105_1000 (ICN_SS idx 1 = tum_ss).
 *    - Internal address decode uses PADDR[9:8]:
 *        00 -> matrix_buffer_ab  (A @ 0x00, B @ 0x40, CTRL @ 0x80)
 *        01 -> control_unit      (regmap @ 0x100)
 *        10 -> matrix_buffer_c   (DATA @ 0x200, CTRL @ 0x280)
 *    - Hardware array is fixed 16x16x16. Each 32-bit APB write packs
 *      32/DATA_W elements (DATA_W = 8 -> four), least-significant lane first.
 */

#include <stdint.h>
#include "soc_ctrl.h"
#include "uart.h"
#include "accel_gemm_data.h"

// Accelerator dimensions (ACC_M/ACC_N/ACC_K/ACC_DATA_W) come from the generated
// accel_gemm_data.h so the firmware and its golden reference can never drift.
#define ELEMS_PER_WORD (32 / ACC_DATA_W) // packed elements per 32-bit APB word

// Low-ACC_DATA_W-bit mask used to truncate each signed element to its field
// before packing. (1u << 32) is undefined in C, so special-case 32-bit data.
#if ACC_DATA_W >= 32
#define DATA_MASK 0xFFFFFFFFu
#else
#define DATA_MASK ((1u << ACC_DATA_W) - 1u)
#endif

// TUM subsystem slot index and accelerator APB base address.
#define ACCEL_SS 1
#define ACCEL_BASE 0x01051000u

// matrix_buffer_ab (PADDR[9:8] == 00)
#define MAT_A_DATA (*(volatile uint32_t *)(ACCEL_BASE + 0x000u))
#define MAT_B_DATA (*(volatile uint32_t *)(ACCEL_BASE + 0x040u))
#define MAT_AB_CTRL (*(volatile uint32_t *)(ACCEL_BASE + 0x080u))

// control_unit (PADDR[9:8] == 01)
#define REG_CTRL (*(volatile uint32_t *)(ACCEL_BASE + 0x100u))
#define REG_STATUS (*(volatile uint32_t *)(ACCEL_BASE + 0x104u))
#define REG_M_DIM (*(volatile uint32_t *)(ACCEL_BASE + 0x108u))
#define REG_N_DIM (*(volatile uint32_t *)(ACCEL_BASE + 0x10Cu))
#define REG_INT_EN (*(volatile uint32_t *)(ACCEL_BASE + 0x110u))
#define REG_INT_STAT (*(volatile uint32_t *)(ACCEL_BASE + 0x114u))
#define REG_K_DIM (*(volatile uint32_t *)(ACCEL_BASE + 0x118u))
#define REG_BUILD_INFO (*(volatile uint32_t *)(ACCEL_BASE + 0x11Cu))
#define REG_HW_STATUS (*(volatile uint32_t *)(ACCEL_BASE + 0x120u))
#define REG_PERF_CTRL (*(volatile uint32_t *)(ACCEL_BASE + 0x124u))
#define REG_PERF_CYCLES (*(volatile uint32_t *)(ACCEL_BASE + 0x128u))
#define REG_PERF_APB_WRITES (*(volatile uint32_t *)(ACCEL_BASE + 0x12Cu))
#define REG_PERF_APB_READS (*(volatile uint32_t *)(ACCEL_BASE + 0x130u))
#define REG_PERF_IN_STALLS (*(volatile uint32_t *)(ACCEL_BASE + 0x134u))
#define REG_PERF_OUT_STALLS (*(volatile uint32_t *)(ACCEL_BASE + 0x138u))

// matrix_buffer_c (PADDR[9:8] == 10)
#define MAT_C_DATA (*(volatile uint32_t *)(ACCEL_BASE + 0x200u))
#define MAT_C_CTRL (*(volatile uint32_t *)(ACCEL_BASE + 0x280u))

// Control / status bit fields.
#define CTRL_START_BIT (1u << 0)
#define CTRL_SOFTRST_BIT (1u << 1)
#define STATUS_BUSY_BIT (1u << 0)
#define STATUS_DONE_BIT (1u << 1)
#define MAT_CTRL_RESET_BIT (1u << 0)
#define PERF_CLEAR_BIT (1u << 0)
#define HW_STATUS_OUT_STALL_SEEN_BIT (1u << 2)
#define HW_STATUS_COUNTER_OVERFLOW_BIT (1u << 3)

// Result sink that the testbench / debugger can observe:
//   0xACCE5500 -> PASS, 0xBADD0000 | mismatch_count -> FAIL.
// main() additionally returns its status (0 = pass): crt0's postMain ORs in
// the done bit and writes it to the 0x01020380 status register, which the
// JTAG-driven tb_didactic polls to detect end-of-computation.
volatile uint32_t accel_result = 0u;

static uint32_t expected_build_info(void) {
  return ((uint32_t)ACC_DATA_W << 24) | ((uint32_t)ACC_K << 16) | ((uint32_t)ACC_N << 8) |
         (uint32_t)ACC_M;
}

int main(void) {
  uart_init();
  uart_print("accel: start\n");

  // Bring the TUM subsystem out of reset and enable its clock.
  ss_init(ACCEL_SS);

  if (REG_BUILD_INFO != expected_build_info()) {
    uart_print("accel: BUILD INFO MISMATCH\n");
    accel_result = 0xBADD0002u;
    return 2;
  }

  // 1. Reset the A/B write pointers (transient, self-clearing).
  MAT_AB_CTRL = MAT_CTRL_RESET_BIT;

  // 2. Stream Matrix A. Each 32-bit word packs ELEMS_PER_WORD elements of
  //    ACC_DATA_W bits, least-significant lane first, matching the buffer's
  //    unpack order. Width-independent: works for any DATA_W dividing 32.
  const uint32_t a_words = (ACC_M * ACC_K) / ELEMS_PER_WORD;
  for (uint32_t w = 0; w < a_words; w++) {
    uint32_t word = 0u;
    for (uint32_t e = 0; e < ELEMS_PER_WORD; e++) {
      uint32_t elem = (uint32_t)accel_A[w * ELEMS_PER_WORD + e] & DATA_MASK;
      word |= elem << (e * ACC_DATA_W);
    }
    MAT_A_DATA = word;
  }

  // 3. Stream Matrix B (same packing).
  const uint32_t b_words = (ACC_K * ACC_N) / ELEMS_PER_WORD;
  for (uint32_t w = 0; w < b_words; w++) {
    uint32_t word = 0u;
    for (uint32_t e = 0; e < ELEMS_PER_WORD; e++) {
      uint32_t elem = (uint32_t)accel_B[w * ELEMS_PER_WORD + e] & DATA_MASK;
      word |= elem << (e * ACC_DATA_W);
    }
    MAT_B_DATA = word;
  }

  // 4. Reset the C capture state / read pointer.
  MAT_C_CTRL = MAT_CTRL_RESET_BIT;

  // 5. (Optional) program the exposed dimension registers for documentation.
  REG_M_DIM = ACC_M;
  REG_N_DIM = ACC_N;
  REG_K_DIM = ACC_K;

  // Clear performance counters after preload/config writes. The subsequent
  // counters cover the start/poll/readback window and the compute phase.
  REG_PERF_CTRL = PERF_CLEAR_BIT;

  // 6. Issue a start pulse to the compute FSM.
  REG_CTRL = CTRL_START_BIT;

  // 7. Wait for completion (STATUS.done). Guard with a timeout so a broken
  //    integration cannot hang the test forever.
  uint32_t timeout = 1000000u;
  while (((REG_STATUS & STATUS_DONE_BIT) == 0u) && (timeout != 0u)) {
    timeout--;
  }

  if (timeout == 0u) {
    uart_print("accel: TIMEOUT waiting for done\n");
    accel_result = 0xBADD0001u;
    return 1; // nonzero exit status -> tb_didactic reports FAILURE
  }

  // 8. Read back all C elements and compare against the golden reference.
  const uint32_t c_count = ACC_M * ACC_N; // 256
  uint32_t mismatches = 0u;
  for (uint32_t i = 0; i < c_count; i++) {
    int32_t c = (int32_t)MAT_C_DATA;
    if (c != accel_golden[i]) {
      mismatches++;
    }
  }

  const uint32_t perf_apb_reads = REG_PERF_APB_READS;
  const uint32_t perf_apb_writes = REG_PERF_APB_WRITES;
  const uint32_t perf_cycles = REG_PERF_CYCLES;
  const uint32_t perf_out_stalls = REG_PERF_OUT_STALLS;
  const uint32_t hw_status = REG_HW_STATUS;

  // 9. Clear the done status (W1C) for a clean end state.
  REG_STATUS = STATUS_DONE_BIT;

    if ((perf_cycles == 0u) || (perf_apb_writes == 0u) || (perf_apb_reads < c_count) ||
      (perf_out_stalls != 0u) ||
      ((hw_status & (HW_STATUS_OUT_STALL_SEEN_BIT | HW_STATUS_COUNTER_OVERFLOW_BIT)) != 0u)) {
    uart_print("accel: PERF FAIL\n");
    accel_result = 0xBADD0003u;
    return 3;
  }

  if (mismatches == 0u) {
    uart_print("accel: PASS\n");
    accel_result = 0xACCE5500u;
    return 0; // exit status 0 -> tb_didactic reports JTAG RETURN OK
  }

  uart_print("accel: FAIL\n");
  accel_result = 0xBADD0000u | (mismatches & 0xFFFFu);
  return (int)(mismatches & 0x7FFFFFFFu); // nonzero -> tb_didactic FAILURE
}
