/*
 * Name: accel.c
 * Contributor(s):
 *    - Group5 (TUM systolic-array AI accelerator)
 * Description:
 *    - Baremetal self-checking functional test for the systolic-array
 *      accelerator integrated in the TUM student subsystem (SS1).
 *    - Streams random signed 16-bit matrices A and B (from accel_gemm_data.h)
 *      through the accelerator, then reads back C = A * B and compares every
 *      element against a precomputed golden reference.
 *    - The test vectors and golden matrix are generated by
 *      scripts/c_code/gen_accel_data.py and reproduce the RTL's signed,
 *      32-bit-wrapping accumulation bit-for-bit.
 * Notes:
 *    - Accelerator APB window base = 0x0105_1000 (ICN_SS idx 1 = tum_ss).
 *    - Internal address decode uses PADDR[9:8]:
 *        00 -> matrix_buffer_ab  (A @ 0x00, B @ 0x40, CTRL @ 0x80)
 *        01 -> control_unit      (regmap @ 0x100)
 *        10 -> matrix_buffer_c   (DATA @ 0x200, CTRL @ 0x280)
 *    - Hardware array is fixed 16x16x16 (DATA_W = 16). Each 32-bit APB write
 *      packs two 16-bit elements, LSB-lane first.
 */

#include <stdint.h>
#include "soc_ctrl.h"
#include "uart.h"
#include "accel_gemm_data.h"

// Accelerator dimensions (ACC_M/ACC_N/ACC_K/ACC_DATA_W) come from the generated
// accel_gemm_data.h so the firmware and its golden reference can never drift.
#define ELEMS_PER_WORD (32 / ACC_DATA_W) // 2 elements per 32-bit APB word

// TUM subsystem slot index and accelerator APB base address.
#define ACCEL_SS 1
#define ACCEL_BASE 0x01051000u

// matrix_buffer_ab (PADDR[9:8] == 00)
#define MAT_A_DATA (*(volatile uint32_t *)(ACCEL_BASE + 0x000u))
#define MAT_B_DATA (*(volatile uint32_t *)(ACCEL_BASE + 0x040u))
#define MAT_AB_CTRL (*(volatile uint32_t *)(ACCEL_BASE + 0x080u))

// control_unit (PADDR[9:8] == 01)
#define REG_CTRL (*(volatile uint32_t *)(ACCEL_BASE + 0x100u))
#define REG_STATUS (*(volatile uint32_t *)(ACCEL_BASE + 0x104u))
#define REG_M_DIM (*(volatile uint32_t *)(ACCEL_BASE + 0x108u))
#define REG_N_DIM (*(volatile uint32_t *)(ACCEL_BASE + 0x10Cu))
#define REG_INT_EN (*(volatile uint32_t *)(ACCEL_BASE + 0x110u))
#define REG_INT_STAT (*(volatile uint32_t *)(ACCEL_BASE + 0x114u))
#define REG_K_DIM (*(volatile uint32_t *)(ACCEL_BASE + 0x118u))

// matrix_buffer_c (PADDR[9:8] == 10)
#define MAT_C_DATA (*(volatile uint32_t *)(ACCEL_BASE + 0x200u))
#define MAT_C_CTRL (*(volatile uint32_t *)(ACCEL_BASE + 0x280u))

// Control / status bit fields.
#define CTRL_START_BIT (1u << 0)
#define CTRL_SOFTRST_BIT (1u << 1)
#define STATUS_BUSY_BIT (1u << 0)
#define STATUS_DONE_BIT (1u << 1)
#define MAT_CTRL_RESET_BIT (1u << 0)

// Result sink that the testbench / debugger can observe:
//   0xACCE5500 -> PASS, 0xBADD0000 | mismatch_count -> FAIL.
// main() additionally returns its status (0 = pass): crt0's postMain ORs in
// the done bit and writes it to the 0x01020380 status register, which the
// JTAG-driven tb_didactic polls to detect end-of-computation.
volatile uint32_t accel_result = 0u;

int main(void) {
  uart_init();
  uart_print("accel: start\n");

  // Bring the TUM subsystem out of reset and enable its clock.
  ss_init(ACCEL_SS);

  // 1. Reset the A/B write pointers (transient, self-clearing).
  MAT_AB_CTRL = MAT_CTRL_RESET_BIT;

  // 2. Stream Matrix A. Each 32-bit word packs two 16-bit elements, LSB lane
  //    first, matching the buffer's unpack order.
  const uint32_t a_words = (ACC_M * ACC_K) / ELEMS_PER_WORD; // 128
  for (uint32_t w = 0; w < a_words; w++) {
    uint32_t lo = (uint32_t)(uint16_t)accel_A[2u * w];
    uint32_t hi = (uint32_t)(uint16_t)accel_A[2u * w + 1u];
    MAT_A_DATA = lo | (hi << 16);
  }

  // 3. Stream Matrix B (same packing).
  const uint32_t b_words = (ACC_K * ACC_N) / ELEMS_PER_WORD; // 128
  for (uint32_t w = 0; w < b_words; w++) {
    uint32_t lo = (uint32_t)(uint16_t)accel_B[2u * w];
    uint32_t hi = (uint32_t)(uint16_t)accel_B[2u * w + 1u];
    MAT_B_DATA = lo | (hi << 16);
  }

  // 4. Reset the C capture state / read pointer.
  MAT_C_CTRL = MAT_CTRL_RESET_BIT;

  // 5. (Optional) program the exposed dimension registers for documentation.
  REG_M_DIM = ACC_M;
  REG_N_DIM = ACC_N;
  REG_K_DIM = ACC_K;

  // 6. Issue a start pulse to the compute FSM.
  REG_CTRL = CTRL_START_BIT;

  // 7. Wait for completion (STATUS.done). Guard with a timeout so a broken
  //    integration cannot hang the test forever.
  uint32_t timeout = 1000000u;
  while (((REG_STATUS & STATUS_DONE_BIT) == 0u) && (timeout != 0u)) {
    timeout--;
  }

  if (timeout == 0u) {
    uart_print("accel: TIMEOUT waiting for done\n");
    accel_result = 0xBADD0001u;
    return 1; // nonzero exit status -> tb_didactic reports FAILURE
  }

  // 8. Read back all C elements and compare against the golden reference.
  const uint32_t c_count = ACC_M * ACC_N; // 256
  uint32_t mismatches = 0u;
  for (uint32_t i = 0; i < c_count; i++) {
    int32_t c = (int32_t)MAT_C_DATA;
    if (c != accel_golden[i]) {
      mismatches++;
    }
  }

  // 9. Clear the done status (W1C) for a clean end state.
  REG_STATUS = STATUS_DONE_BIT;

  if (mismatches == 0u) {
    uart_print("accel: PASS\n");
    accel_result = 0xACCE5500u;
    return 0; // exit status 0 -> tb_didactic reports JTAG RETURN OK
  }

  uart_print("accel: FAIL\n");
  accel_result = 0xBADD0000u | (mismatches & 0xFFFFu);
  return (int)(mismatches & 0x7FFFFFFFu); // nonzero -> tb_didactic FAILURE
}
