#ifndef __ACCEL_GEMM_DATA_H__
#define __ACCEL_GEMM_DATA_H__

#include <stdint.h>

/*
 * Auto-generated by sim/common/c_code/gen_accel_data.py
 * Variant: int8_8x8, case: random (seed 0xACCE).
 * Do not edit by hand; rerun the generator instead.
 *
 * Random signed 8-bit GEMM test vectors for the systolic-array
 * accelerator.  The golden matrix is C = A * B with
 *   C[i][j] = sum_k A[i][k] * B[k][j]
 * accumulated in 32-bit two's-complement arithmetic (wraps, no saturation),
 * matching rtl/MAC/mac_pe.sv exactly.
 *
 * Layout (row-major, matching the hardware buffers):
 *   A[i][k] -> accel_A[i * ACC_K + k]
 *   B[k][j] -> accel_B[k * ACC_N + j]
 *   C[i][j] -> accel_golden[i * ACC_N + j]
 */

#define ACC_VARIANT "int8_8x8"
#define ACC_M 8
#define ACC_N 8
#define ACC_K 8
#define ACC_DATA_W 8
#define ACC_ACC_W 32

static const int8_t accel_A[ACC_M * ACC_K] = {
    39, 34, 111, 113, -110, 65, -49, 66,
    -81, 71, 71, 23, 77, -104, 56, 34,
    -38, 32, 127, -54, -19, 24, -101, -82,
    -8, -48, 86, 28, -73, -3, -35, -35,
    -101, 86, -90, -42, -18, -69, 70, -123,
    -54, -38, -54, -5, -72, -19, 82, -98,
    121, -62, -66, -102, 84, 76, 31, -123,
    119, -59, 100, 69, 42, -41, -20, -49,
};

static const int8_t accel_B[ACC_K * ACC_N] = {
    -7, 14, 31, -73, 106, -102, -76, -105,
    114, -86, 70, -116, -50, 118, -12, -54,
    -37, 54, 114, 123, -24, -30, 124, 46,
    119, -105, -101, 92, 24, 77, -101, -9,
    46, 8, -112, 126, 119, -115, -57, -76,
    -53, -81, 126, -66, -124, -28, 116, -30,
    107, -12, -125, -23, 92, -58, -109, -91,
    9, -54, -51, -126, 89, -88, 124, -51,
};

static const int32_t accel_golden[ACC_M * ACC_N] = {
    -211, -17370, 28099, -8081, -17302, 13269, 26314, 5661,
    24123, 711, -22232, 19520, 16949, 4098, -6556, -1832,
    -20902, 12788, 42953, 18392, -31799, 14271, 28414, 22687,
    -12525, 7689, 17326, 15521, -14490, 8317, 12308, 17744,
    18055, 1987, -12284, -1363, -11947, 30682, -30134, 5540,
    3036, 5392, -9567, 3892, -10038, 14939, -20821, 8861,
    -15565, 14958, 4755, 1210, 7539, -28294, -20937, -16687,
    -1524, 11438, -881, 31437, 18701, -14997, -13951, -2973,
};

#endif /* __ACCEL_GEMM_DATA_H__ */
